url: 'https://romakoch.com'

title: romakoch
description: >
  Изливаю свет собственного величия на рабочее трудонаселение.

author:
  name: Роман Кох
  avatar: "/assets/img/logo.webp"
  email: mail@romakoch.com
  description: > 
    Роман Кох — эксперт в области электронной коммерции с более чем 15-летним опытом, пишет о менеджменте, e-commerce и методах продуктивности.

google_tag_manager: GTM-MF37N24

social_links:
  - { title: linkedin, visible: true, user_url: "https://www.linkedin.com/in/fatnotbad/" }
  - { title: habr, visible: false, user_url: "https://habr.com/ru/users/FatNotBad/" }
  - { title: vc, visible: false, user_url: "https://vc.ru/u/245143-roman-koh" }
  - { title: e-xecutive, visible: false, user_url: "https://www.e-xecutive.ru/users/1898956-roman-koh" }

permalink: "/blog/:title/"

feed:
  excerpt_only: true

plugins:
  - jekyll-postcss-v2
  - jekyll-feed
  - jekyll-sitemap
  - jemoji

exclude:
  - Gemfile
  - Gemfile.lock
  - "package*.json"
  - "*.config.js"